#!/usr/bin/env bash

#Script to take sams and merge 

#PBS -W group_list=bhurwitz
#PBS -q standard
#PBS -l jobtype=cluster_only
#PBS -l select=1:ncpus=2:mem=3gb:pcmem=2gb
#PBS -l pvmem=6gb
#PBS -l walltime=24:10:00
#PBS -l cput=24:10:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

cd $PBS_O_WORKDIR

CONFIG="$PRJ_DIR/scripts/config.sh"

if [ -e $CONFIG ]; then
    . "$CONFIG"
else
    echo Missing config \"$CONFIG\"
    exit 1
fi

COMMON="$WORKER_DIR/common.sh"

if [ -e $COMMON ]; then
  . "$COMMON"
else
  echo Missing common \"$COMMON\"
  exit 1
fi

TMP_FILES=$(mktemp)

get_lines $FILE_LIST $TMP_FILES $PBS_ARRAY_INDEX $STEP_SIZE

NUM_FILES=$(lc $TMP_FILES)

echo Found \"$NUM_FILES\" files to process

while read FILE; do
    if [[ ! -s $BAM_OUT_DIR/$FILE.bam ]]; then
        echo Converting and sorting \'sam\'s in $FILE.sam
        samtools view -bT $BOWTIE2_DB.fasta $FILE \
            | samtools sort - \
            > $BAM_OUT_DIR/$FILE.bam
    else
        echo $SHORT_NAME already done
    fi
done < $TMP_FILES

