#!/usr/bin/env bash

#Script to take sams and merge 

#PBS -W group_list=bhurwitz
#PBS -q standard
#PBS -l jobtype=cluster_only
#PBS -l select=1:ncpus=2:mem=3gb:pcmem=2gb
#PBS -l pvmem=6gb
#PBS -l walltime=24:10:00
#PBS -l cput=24:10:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

cd $PBS_O_WORKDIR

CONFIG="$PRJ_DIR/scripts/config.sh"

if [ -e $CONFIG ]; then
    . "$CONFIG"
else
    echo Missing config \"$CONFIG\"
    exit 1
fi

COMMON="$WORKER_DIR/common.sh"

if [ -e $COMMON ]; then
  . "$COMMON"
else
  echo Missing common \"$COMMON\"
  exit 1
fi

TMP_FILES=$(mktemp)

get_lines $DIR_LIST $TMP_FILES $PBS_ARRAY_INDEX $STEP_SIZE

NUM_DIRS=$(lc $TMP_FILES)

echo Found \"$NUM_DIRS\" files to process

while read DIR; do
    
    SHORT_NAME=$(basename $DIR ".fa")

    NEW_DIR=$CAT_OUT_DIR/$(basename $DIR ".fa")

    if [[ ! -d $NEW_DIR ]]; then
        mkdir -p $NEW_DIR 
    fi

    if [[ ! -s $CAT_OUT_DIR/$SHORT_NAME.bam ]]; then
        echo Converting and sorting \'sam\'s in $SHORT_NAME.fa
        find $DIR -type f -iname \*.sam -print0 \
            | xargs -0 -I file samtools view -bT $BOWTIE2_DB.fasta file \
            | samtools sort - \
            > $NEW_DIR/file.bam

        CHECK1=$(find $DIR -iname \*.sam | wc -l)
        CHECK2=$(find $NEW_DIR -iname \*.bam | wc -l)

        if [ "$CHECK1" = "$CHECK2" ]; then
            echo Merging into $SHORT_NAME.bam
            find $NEW_DIR -iname "\*.bam" -print0 \
                | xargs -0 -I file samtools merge $SHORT_NAME.bam file
        else
            echo Something went wrong with the conversion or sorting
            exit 1
        fi
    else
        echo $SHORT_NAME already done
    fi

done < $TMP_FILES

