#!/usr/bin/env bash

#PBS -W group_list=bhurwitz
#PBS -q standard
#PBS -l jobtype=serial
#PBS -l select=1:ncpus=12:mem=23gb:pcmem=2gb
#PBS -l pvmem=46gb
#PBS -l walltime=24:00:00
#PBS -l cput=24:00:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

if [ -n "$PBS_O_WORKDIR" ]; then
    cd $PBS_O_WORKDIR
fi

CONFIG="./config.sh"

if [ -e $CONFIG ]; then
    . "$CONFIG"
else
    echo MIssing config \"$CONFIG\"
    exit 12385
fi

COMMON="$WORKER_DIR/common.sh"

if [ -e $COMMON ]; then
  . "$COMMON"
else
  echo Missing common \"$COMMON\"
  exit 1
fi

cd $CONTIG_DIR

#fix annotation so there is only a single header
find ./contig-out/ -iname \*.tab -print0 | xargs -0 -I file cat file > $CONTIGS_ANNOT
head -1 $CONTIGS_ANNOT > header.temp
egrep -v '^prot\s.+' $CONTIGS_ANNOT > temp.tab
cat header.temp temp.tab > temp2.tab
mv temp2.tab $CONTIGS_ANNOT
mv temp.tab annotation_backup.tab

#fix annotation so prot numbers are sequential (and smaller)
if [ -n "$PBS_O_WORKDIR" ]; then
    cd $PBS_O_WORKDIR
fi
module load R
Rscript $SCRIPT_DIR/FIX-ANNOTATION.R

#anvi-gen-contigs-database -f $CONTIGS -o $ANVI_CONTIG_DB
#svr_assign_to_dna_using_figfams < $CONTIGS > svr_assign_to_dna_using_figfams.txt
anvi-populate-genes-table -c $ANVI_CONTIG_DB -p default_matrix -i $CONTIGS_ANNOT
#anvi-export-genes-table -c $ANVI_CONTIG_DB -o rast_annotation.txt

