#!/usr/bin/env bash

#PBS -W group_list=bhurwitz
#PBS -q standard
#PBS -l jobtype=cluster_only
#PBS -l select=1:ncpus=12:mem=23gb:pcmem=2gb
#PBS -l pvmem=46gb
#PBS -l walltime=05:30:00
#PBS -l cput=05:30:00
#PBS -o out/
#PBS -e out/
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

cd $PBS_O_WORKDIR

CONFIG="./config.sh"

if [ -e $CONFIG ]; then
    . "$CONFIG"
else
    echo Missing config \"$CONFIG\"
    exit 12385
fi

COMMON="$WORKER_DIR/common.sh"

if [ -e $COMMON ]; then
  . "$COMMON"
else
  echo Missing common \"$COMMON\"
  exit 1
fi

cd $CAT_OUT_DIR

array=( DNA_1 DNA_2 DNA_3 DNA_4 )

for i in "${array[@]}"; do
    find ./ -iname \*$i\*.sam -print0 \
    | xargs -0 -I file cat file \
    | samtools view -bT --threads 12 \
    $BOWTIE2_DB.fasta - > all$i.bam 
    gzip -v -c all$i.bam > all$i.bam.gz
done

