#!/usr/bin/env bash

#PBS -W group_list=bhurwitz
#PBS -q standard
#PBS -l select=1:ncpus=6:mem=252gb:pcmem=42gb
#PBS -l walltime=24:00:00
#PBS -l cput=24:00:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

if [ -n $PBS_O_WORKDIR ]; then
    cd $PBS_O_WORKDIR
fi

#need gsl library for 'import anvio.concoct'
#ua hpc library is good enough
#module load gsl
echo "If LD_LIBRARY_PATH doesn't have libgsl.so.0 there, you are screwed"
echo $LD_LIBRARY_PATH
find $LD_LIBRARY_PATH -iname libgsl.so.0


CONFIG="./config.sh"

if [ -e $CONFIG ]; then
    . "$CONFIG"
else
    echo MIssing config \"$CONFIG\"
    exit 12385
fi

COMMON="$WORKER_DIR/common.sh"

if [ -e $COMMON ]; then
  . "$COMMON"
else
  echo Missing common \"$COMMON\"
  exit 1
fi

#No concot binning because we already know which contigs are grouped by genome

cd $FINAL_BAM_DIR
anvi-merge \
    --skip-concoct-binning \
    -W */RUNINFO.cp -o ALL-DNA-MERGED -c $ANVI_CONTIG_DB
